### ISSUE TITLE
Inconsistency (incompatibility) with raisimGymTorch?

### ISSUE THREAD

**Issue by joonkyu4220** [ZhaomingXie/soccer_juggle_release#1]
Hello, Dr. Xie.
A fan of your work here speaking.

I forked and cloned your repository to run the code myself.
I ran into some inconsistencies in [Environment.hpp](https://github.com/ZhaomingXie/soccer_juggle_release/blob/master/Environment.hpp) with [RaisimGymEnv.hpp](https://github.com/ZhaomingXie/raisimLib/blob/master/raisimGymTorch/raisimGymTorch/env/RaisimGymEnv.hpp), while setting up.

Virtual functions of **setEnvironmentTask** and **getState**  are not implemented in RaisimGymEnv.hpp, but it is marked **_final_** in [Environment.hpp](https://github.com/ZhaomingXie/soccer_juggle_release/blob/master/Environment.hpp).
Also, **statedim_** is not declared anywhere in [RaisimGymEnv.hpp](https://github.com/ZhaomingXie/raisimLib/blob/master/raisimGymTorch/raisimGymTorch/env/RaisimGymEnv.hpp), but appears in [Environment.hpp](https://github.com/ZhaomingXie/soccer_juggle_release/blob/master/Environment.hpp).
I think something is missing or is not being updated.

I apologize and appreciate you in advance in case it's me who missed something.

**Comment by ZhaomingXie** [comment]
Hi

Thanks for your interest. 
Maybe it is because you are not on the right branch of raisimLib? I am using the juggling branch for my soccer juggling environment: https://github.com/ZhaomingXie/raisimLib/tree/juggling.

Let me know if you still run into problems!

**Comment by joonkyu4220** [comment]
What an embarrassing mistake I have made.
Sorry I bothered you with a ridiculous question.
Now it runs just fine, and I'm ready to enjoy your fabulous work.
(Except that I now have a "position is nan" issue, which I think I'll be able to figure out myself.)
Thank you for your quick and kind reply.
I'll close the issue.
