### ISSUE TITLE
Nan Issue for calculating rewards

### ISSUE THREAD

**Issue by JeonghyunNam** [ZhaomingXie/soccer_juggle_release#2]
Hello, sir.
To me, it's an honor to see your amazing work.
I want to replay this work myself,
so I cloned the repository and running it.

But, I got nan issue for calculating rewards.
and I found that caused by nan value of some elements in gc, gv variables.

Is there something I'm missing out on?

**Comment by ZhaomingXie** [comment]
Hi

Can you specify how you get the nan issue? Can you run test_policy.py ok? Does it happen at the very beginning of vec_ppo.py or after a few iterations? Do you know which elements of gc, gv is causing the problem?

**Comment by JeonghyunNam** [comment]
Hello

Sorry for late response.
I can run test_policy.py partially.
At test_policy.py line 62:
      obs, rew, done, _ = env.step(act)
causes error.

Error message:
[2022:08:28:02:22:37 Reward.hpp:46] position is nan
[2022:08:28:02:22:37 Reward.hpp:46] position is nan
[2022:08:28:02:22:37 Reward.hpp:46] position is nan

So, I printed out gc_ and gv_ values in error-relevant part(computeReward in Environment.hpp)

Followings are the result:
gc_ :
-nan, -nan, -nan, nan, nan,  nan,  nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan, -nan ,-nan ,-nan

gv_:
 nan, nan, nan,-nan,-nan,-nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan

**Comment by ZhaomingXie** [comment]
Hi

I have trouble reproducing the error. Does gc_, gv_ become nan at the very beginning? If not, how many steps does it take to become nan, and what is gc_, gv_ before they become nan?

**Comment by JeonghyunNam** [comment]
Hello

Yes, sir. 
From the beginning, gc_ and gv_ values ​​point to nan.

I found that act value contains nan(test_policy.py line 60).

Nan is appeared at some rows of act value : (below is row number)
[0, 4, 10, 14, 20, 22, 23, 25, 26, 28, 30, 39, 67, 68, 70, 72, 76, 77, 78, 81, 85, 86, 88, 91, 97, 106, 107, 111, 113, 119, 122, 124, 126, 131, 140, 142, 151, 154, 159, 163, 166, 169, 170, 174, 175, 177, 183, 186, 190, 192, 197, 199, 200, 205, 213, 215, 217, 219, 220, 222, 223, 226, 228, 229, 230, 231, 233, 238, 239, 240, 245, 246, 252, 255, 263, 264, 265, 269, 271, 272, 274, 278, 282, 288, 295, 296, 304, 305, 314, 315, 316, 321, 325, 330, 332, 334, 339, 342, 345, 351, 354, 357, 360, 363, 364, 367, 368, 372, 373, 375, 376, 379, 384, 386, 387, 393, 396, 404, 407, 409, 412, 413, 414, 415, 416, 422, 424, 438, 439, 440, 442, 443, 449, 451, 454, 457, 462, 466, 467, 473, 475, 478, 480, 482, 495, 497, 515, 517, 520, 522, 524, 525, 534, 536, 540, 551, 562, 564, 566, 575, 576, 577, 578, 580, 582, 583, 588, 589, 590, 601, 602, 605, 613, 617, 620, 624, 629, 631, 634, 635, 640, 641, 643, 656, 657, 659, 661, 663, 664, 665, 667, 670, 681, 683, 685, 687, 693, 699, 701, 705, 706, 707, 708, 710, 715, 716, 719, 725, 730, 739, 744, 747, 748, 753, 758, 764, 768, 770, 774, 776, 779, 783, 790, 791, 793, 798]

Does this have anything to do with the previous issue?
Thank you!

**Comment by ZhaomingXie** [comment]
sorry, I cannot reproduce this error, and act value shouldn't be that high dimensional. It is just joint torques for the humanoid,  defined on line 96 of Environment.hpp.

**Comment by joonkyu4220** [comment]
I had the same issue, and I fixed it by moving the motion data file (_around_the_world.txt_ and _around_the_world_right.txt_) from **raisimLib/raisimGymTorch/raisimGymTorch/env/envs/soccer_juggle_release/** to the resource directory, which is **raisimLib/rsc/**, and changing the code from `std::ifstream infile("around_the_world.txt");` and `std::ifstream infile("around_the_world_right.txt");` to `std::ifstream infile(resourceDir_ + "/around_the_world.txt");` and `std::ifstream infile(resourceDir_ + "/around_the_world_right.txt");`, respectively.

The problem was that the matrix, which is supposed to keep the motion data, named `reference_`, was initialized to zero matrix and was never modified, because `infile` was empty due to the incorrect file path.
Zero quaternions (0, 0, 0, 0) passed to the physics engine gives NaN issue.

**Comment by JeonghyunNam** [comment]
> sorry, I cannot reproduce this error, and act value shouldn't be that high dimensional. It is just joint torques for the humanoid, defined on line 96 of Environment.hpp.

Sorry for late response.
Finally, by joonkyu4220, I solved the problem. Thank you for your trial! :)




> I had the same issue, and I fixed it by moving the motion data file (_around_the_world.txt_ and _around_the_world_right.txt_) from **raisimLib/raisimGymTorch/raisimGymTorch/env/envs/soccer_juggle_release/** to the resource directory, which is **raisimLib/rsc/**, and changing the code from `std::ifstream infile("around_the_world.txt");` and `std::ifstream infile("around_the_world_right.txt");` to `std::ifstream infile(resourceDir_ + "/around_the_world.txt");` and `std::ifstream infile(resourceDir_ + "/around_the_world_right.txt");`, respectively.
> 
> The problem was that the matrix, which is supposed to keep the motion data, named `reference_`, was initialized to zero matrix and was never modified, because `infile` was empty due to the incorrect file path. Zero quaternions (0, 0, 0, 0) passed to the physics engine gives NaN issue.

I really appreciated sharing your method!
